import { Hatchet, Context } from '@hatchet-dev/typescript-sdk';
import { SimulatedMetricsSource } from './metrics';
import { computeValueSummary, ValueSummary } from './valueMath';

/**
 * WHY THIS EXISTS:
 * This function builds and registers the Value Digest workflow using Hatchet V1 APIs.
 * It demonstrates a cron trigger and a static fan-out/fan-in DAG (Directed Acyclic Graph).
 * A static DAG is used here for maximum visual clarity in the Hatchet dashboard demo.
 * In a production environment, you would use dynamic fan-out (e.g. `await childWorkflow.runMany()`)
 * to scale over an arbitrary number of users.
 */
export function registerValueDigestWorkflow(hatchet: Hatchet) {
  const metricsSource = new SimulatedMetricsSource();

  // 1. Define the workflow with a cron trigger
  const valueDigestWorkflow = hatchet.workflow({
    name: 'value-digest',
    description: 'Computes a Value Digest demonstrating value generated by Hatchet for customers.',
    on: {
      // Runs daily at 8:00 AM UTC
      cron: '0 8 * * *',
    },
  });

  // 2. Fetch Users Task
  // This is the starting point of the DAG. It identifies which users we need to process.
  const fetchUsersTask = valueDigestWorkflow.task({
    name: 'fetch-users',
    fn: async (input: any, ctx: Context<any>) => {
      ctx.log('Fetching active users for value digest generation...');
      const users = await metricsSource.getUsers();
      ctx.log(`Found ${users.length} active users.`);
      return { users };
    }
  });

  // 3. Fan-out: Compute Summary per User
  // These tasks run in parallel, demonstrating Hatchet's ability to fan out.
  // Each task has its own retry policy (simulating transient network/DB failures).
  const acmeComputeTask = valueDigestWorkflow.task({
    name: 'compute-acme',
    parents: [fetchUsersTask],
    retries: 3, // Hatchet V1 Retry Policy: Retries independently on failure
    fn: async (input: any, ctx: Context<any>) => {
      ctx.log('Computing value summary for Acme Corp...');
      
      // Deterministic fail to show the visual retry and value generation in Hatchet dashboard!
      if (ctx.retryCount() < 1) {
        ctx.log('Simulating a transient failure for demonstration purposes...');
        throw new Error('Simulated transient failure');
      }

      const metrics = await metricsSource.getUserMetrics('user-acme');
      const summary = computeValueSummary(metrics);
      return summary;
    }
  });

  const globexComputeTask = valueDigestWorkflow.task({
    name: 'compute-globex',
    parents: [fetchUsersTask],
    retries: 3, // Hatchet V1 Retry Policy: Retries independently on failure
    fn: async (input: any, ctx: Context<any>) => {
      ctx.log('Computing value summary for Globex Inc...');
      const metrics = await metricsSource.getUserMetrics('user-globex');
      const summary = computeValueSummary(metrics);
      return summary;
    }
  });

  // 4. Fan-in: Aggregate and format the digest
  // This task waits for all 'compute' tasks to finish before running.
  valueDigestWorkflow.task({
    name: 'aggregate-digest',
    parents: [acmeComputeTask, globexComputeTask],
    fn: async (input: any, ctx: Context<any>) => {
      ctx.log('Aggregating value summaries...');
      
      // Retrieve the results from the parent tasks (V1 syntax uses await parentOutput)
      const acmeSummary = (await ctx.parentOutput('compute-acme')) as unknown as ValueSummary;
      const globexSummary = (await ctx.parentOutput('compute-globex')) as unknown as ValueSummary;

      const summaries = [acmeSummary, globexSummary];

      // Format the final output visually for the console demo
      console.log('\n======================================================');
      console.log('                 HATCHET VALUE DIGEST                 ');
      console.log('======================================================\n');
      
      for (const s of summaries) {
        console.log(`🏢 Customer: ${s.userName}`);
        console.log(`✅ Recovered Tasks: ${s.runsRecovered}`);
        console.log(`⏱️  Engineering Time Saved: ~${s.hoursSaved} hours\n`);
      }
      
      console.log('======================================================\n');

      return { success: true, count: summaries.length };
    }
  });

  return valueDigestWorkflow;
}
